"""Create payment transactions table

Revision ID: ecc23277b011
Revises: 978b590022d8
Create Date: 2026-06-13 16:31:17.148914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc23277b011'
down_revision: Union[str, Sequence[str], None] = '978b590022d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymenttransactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('authorization_url', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymenttransactions_id'), 'paymenttransactions', ['id'], unique=False)
    op.create_index(op.f('ix_paymenttransactions_invoice_id'), 'paymenttransactions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_paymenttransactions_reference'), 'paymenttransactions', ['reference'], unique=True)
    op.create_index(op.f('ix_paymenttransactions_status'), 'paymenttransactions', ['status'], unique=False)
    op.create_index(op.f('ix_paymenttransactions_workspace_id'), 'paymenttransactions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paymenttransactions_workspace_id'), table_name='paymenttransactions')
    op.drop_index(op.f('ix_paymenttransactions_status'), table_name='paymenttransactions')
    op.drop_index(op.f('ix_paymenttransactions_reference'), table_name='paymenttransactions')
    op.drop_index(op.f('ix_paymenttransactions_invoice_id'), table_name='paymenttransactions')
    op.drop_index(op.f('ix_paymenttransactions_id'), table_name='paymenttransactions')
    op.drop_table('paymenttransactions')
    # ### end Alembic commands ###
